Feat/3.3.1
agilekidz/kidzbracket pull request #16
Opened 2020-05-05 06:46 UTC by Noxemia

Completed 3.3.1

2020-05-05 06:50 UTC, Noxemia commented
Btw, this kinda cucks our design on the cards, but I think that in a foreseeable future we will need to do a big changeroonie on that anyways soo

2020-05-05 06:54 UTC, Noxemia commented
It looks kinda wonk that I have "false as sorted in my query" but it is because I have the big retard but it also has a real reason. The tournaments are already ordered by creation time atm and I checked if my sort actually worked by reversing it afterwards and it kinda seems like it works. When we sort by starting time/date later this is an easy fix so just don't mind it xd

2020-05-06 13:05 UTC, rosengrenen requested changes

2020-05-06 13:05 UTC, rosengrenen commented on packages/backend/src/modules/tournament/tournaments.query.ts
> +		if (sort) {
use order by in query instead of sorting afterward

2020-05-06 13:05 UTC, rosengrenen commented on packages/frontend/src/screens/app/screens/home/home-logic.tsx
> +import React from 'react';
this file is unnecessary, just display homeview from homedata

2020-05-06 13:05 UTC, rosengrenen commented on packages/frontend/src/screens/app/screens/home/home-view.tsx
> +interface Tournaments {
should this interface be named Props instead of Tournaments?

2020-05-06 13:05 UTC, rosengrenen commented on packages/frontend/src/screens/app/screens/home/home-view.tsx
> +				{tournaments.map(yeet => (
rename yeet to tournament

2020-05-06 13:05 UTC, rosengrenen commented on packages/frontend/src/screens/app/screens/home/components/tournament-card.tsx
>  interface TCProps {
should probably be named TournamentCardProps or just Props instead of abbreviated TCProps

2020-05-06 13:05 UTC, rosengrenen commented on packages/backend/src/modules/tournament/tournaments.query.ts
> +	async tournaments(@Arg('sort', { nullable: true }) sort?: boolean): Promise<GQLTournament[]> {
would it be better to make the orderBy field be an input type containing the field to order by and whether to order in ascending or descending order?

2020-05-06 13:06 UTC, SantaPoro commented on packages/backend/src/index.ts
> +			let tournament = tournamentRepository.create({ name, description, game });
initialize the variables inside the object instead of outside it

2020-05-06 13:06 UTC, SantaPoro commented on packages/frontend/src/screens/app/screens/home/home-data.tsx
> +		tournaments(sort: false) {
Why is it false?

2020-05-07 14:46 UTC, rosengrenen approved these changes

2020-05-07 16:32 UTC, SantaPoro approved these changes

2020-05-07 16:32 UTC, merged