[Feat] 1.1.2 Generate match bracket from teams
agilekidz/kidzbracket pull request #2
Opened 2020-04-24 14:21 UTC by rosengrenen

2020-04-24 19:59 UTC, Noxemia submitted a review, later dismissed
looks cool

2020-04-24 21:28 UTC, cajoho99 requested changes
Looks good but should probably merge with master and change the types before merging

2020-04-24 21:28 UTC, cajoho99 commented on packages/backend/src/generate-bracket.ts
> +}
Shouldn't this use the already defined types?

2020-04-24 21:52 UTC, cajoho99 approved these changes
Ser superbra ut!

2020-04-25 08:55 UTC, SantaPoro approved these changes

2020-04-25 12:49 UTC, merged