Feat/2.5.1
agilekidz/kidzbracket pull request #3
Opened 2020-04-24 18:30 UTC by Noxemia

2020-04-24 20:06 UTC, Noxemia commented
This includes 2.5.2 cuz me and git be big friendos

2020-04-24 21:54 UTC, rosengrenen requested changes
remove oauth creds from env example

2020-04-24 21:54 UTC, rosengrenen commented on packages/frontend/.env.example
> +FACEBOOK_OAUTH2_CLIENT_ID=2696370720593869
why u leak my oauth credentials :c

2020-04-25 03:30 UTC, Noxemia commented
men kolla vad snyggt de e

2020-04-25 06:53 UTC, rosengrenen approved these changes

2020-04-25 08:39 UTC, SantaPoro approved these changes

2020-04-25 09:07 UTC, merged